import type { Metadata } from "next";
import Link from "next/link";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <ul style={{ padding: 0, listStyle: "none", textAlign: "center" }}>
            <h1>Nav Bar</h1>
            <li style={{display: "inline", marginRight: "10px"}}>
              <Link href="/">Home</Link>
            </li>
            <li style={{display: "inline", marginRight: "10px"}}>
              <Link href="/about">About Us</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
